### ISSUE TITLE
How to use it ? 

### ISSUE THREAD

**Issue by jozefrebjak** [tkspuk/napalm-vrp#1]
How can I get this working ? Just copy files from napalm_vrp to napalm directory ?

**Comment by tkspuk** [comment]
This has not yet officially released and should be publish to the napalm community soon,
If you want to experience it，you can install as 
`pip install -i https://test.pypi.org/simple/ napalm-vrp`

The Demo code as below
```
>>> from napalm import get_network_driver
>>> driver = get_network_driver('vrp')
>>> device = driver('192.168.76.10', 'dbarroso', 'this_is_not_a_secure_password')
>>> device.open()
```
